module IC where
  
import Common

waxOn = "LRFKQ YUQFJ KXYQV NRTYS FRZRM ZLYGF VEULQ FPDBH LQDQR RCRWD NXEUO QQEKL AITGD PHCSP IJTHB SFYFV LADZP BFUDK KLRWQ AOZMI XRPIF EFFEC LHBVF UKBYE QFQOJ WTWOS ILEEZ TXWJL KNGBQ QMBXQ CQPTK HHQRQ DWFCA YSSYO QCJOM WUFBD FXUDZ HIFTA KCZVH SYBLO ETSWC RFHPX PRBSS HSJXD FILEB XWBCT OAYAX ZFBJB KRXIR IMQPZ WMSHL PJHTA ZHBUX HWADL PTOYE ZIWKM GSOVQ ZGDIX RPDDZ PLCRW NQWQE CYJYI BFJYK MJFQW LTVZK QTPVO LPHCK CYUFD QMLGL IMKLF ZKTGY GDTTN HCVPF DFBRP ZLKVS HWYWS HTDGM BQBKK XCVGU MONMW VYTBY TNUQH MFJAQ TGNGC WKUZY AMNER PHFMW EVHWL EZOHY EEHBR"

waxOff = "NUFTD WHFTW HFQUU VZXCX FFTNA XMHMT MHFHC XFFTZ AHXMT YUCXM HHAXN TFXNJ HZTNX VATCU ZUNAH ATNTZ XDFTZ MUTAU ZAXMH LXCNT NXACX WXMUN DVTNH OCTDH YUCFQ UTRZH CXFFT ZATCX FFQHV MUHZD UVZXD ATCHX YHFFT NXTRC XZMUF QUDHX ZXCCX ZAUHJ XCHXD YUAAH MUNFT DWTVD XZMTV ZNHZR VXRRH TXJTN AUDFH UZAHL HFTWX XZFQU UDTYC XAAVA ATXFX CXAAU CUFTW HFTTR ZHCXF FTZAT QXVZH ZACTM VGHTZ ULTZM XWUZA XNUXW HTXJJ HDTFQ UDYHU RXXRC XZMHN HZUUM TJUDX CXWOH UZAXA XNXZX CCXGH TZUDY UDDTU JTNUZ AHUCH DTZTM XAHDF HUZAH LHFHF QUMXZ ZTVZH MUXMU NNXCR TWUZA TFVHR HCUCX"